<?xml version="1.0"?>
<robot name="p3at" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Basic dimensions (approx): chassis 0.50 x 0.45 x 0.20 m -->
  <xacro:property name="chassis_length" value="0.50"/>
  <xacro:property name="chassis_width"  value="0.45"/>
  <xacro:property name="chassis_height" value="0.20"/>
  <xacro:property name="chassis_mass"   value="35.0"/>

  <!-- Wheel geometry (approx) -->
  <xacro:property name="wheel_radius"   value="0.11"/>
  <xacro:property name="wheel_width"    value="0.06"/>
  <xacro:property name="wheel_mass"     value="2.0"/>

  <!-- Track width and wheelbase for plugin -->
  <xacro:property name="track_width"    value="0.40"/>
  <xacro:property name="wheelbase"      value="0.35"/>

  <!-- Camera mount -->
  <xacro:property name="cam_x" value="0.20"/>
  <xacro:property name="cam_y" value="0.00"/>
  <xacro:property name="cam_z" value="0.25"/>

  <link name="base_footprint"/>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="20" velocity="20"/>
      <dynamics damping="0.2" friction="0.2"/>
    </joint>
  </xacro:macro>

  <!-- 4 wheels (skid-steer) -->
  <xacro:wheel name="front_left_wheel"  x="${ wheelbase/2.0}" y="${ track_width/2.0}"/>
  <xacro:wheel name="rear_left_wheel"   x="${-wheelbase/2.0}" y="${ track_width/2.0}"/>
  <xacro:wheel name="front_right_wheel" x="${ wheelbase/2.0}" y="${-track_width/2.0}"/>
  <xacro:wheel name="rear_right_wheel"  x="${-wheelbase/2.0}" y="${-track_width/2.0}"/>

  <!-- RGB-D camera link -->
  <link name="camera_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="Blue">
        <color rgba="0.2 0.2 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_to_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${cam_x} ${cam_y} ${cam_z}" rpy="0 0 0"/>
  </joint>

  <!-- Optical frame for depth images -->
  <link name="camera_depth_optical_frame"/>
  <joint name="camera_to_depth_optical" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_depth_optical_frame"/>
    <!-- REP 103 optical frame: Z forward, X right, Y down -->
    <origin xyz="0 0 0" rpy="-1.57079632679 0 -1.57079632679"/>
  </joint>

  <!-- Gazebo: friction and plugins -->
  <gazebo reference="front_left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>
  <gazebo reference="rear_left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>
  <gazebo reference="front_right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>
  <gazebo reference="rear_right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <!-- Skid-steer drive plugin (preferred). If your system lacks this plugin, switch to libgazebo_ros_diff_drive.so. -->
  <gazebo>
    <plugin name="skid_steer_drive" filename="libgazebo_ros_skid_steer_drive.so">
      <robotNamespace>/</robotNamespace>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <broadcastTF>true</broadcastTF>

      <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
      <leftRearJoint>rear_left_wheel_joint</leftRearJoint>
      <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
      <rightRearJoint>rear_right_wheel_joint</rightRearJoint>

      <wheelSeparation>${track_width}</wheelSeparation>
      <wheelDiameter>${2.0*wheel_radius}</wheelDiameter>

      <torque>15</torque>
      <updateRate>50</updateRate>
    </plugin>
  </gazebo>

  <!-- Depth camera plugin. Publishes:
       /camera/depth (sensor_msgs/Image)
       /camera/depth/camera_info (sensor_msgs/CameraInfo)
       /camera/depth/points (sensor_msgs/PointCloud2) -->
  <gazebo reference="camera_link">
    <sensor type="depth" name="depth_camera">
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.2</near>
          <far>6.0</far>
        </clip>
      </camera>
      <plugin name="depth_camera_controller" filename="libgazebo_ros_depth_camera.so">
        <robotNamespace>/</robotNamespace>
        <cameraName>camera</cameraName>
        <frameName>camera_depth_optical_frame</frameName>
        <imageTopicName>camera/rgb/image_raw</imageTopicName>
        <cameraInfoTopicName>camera/rgb/camera_info</cameraInfoTopicName>
        <depthImageTopicName>camera/depth</depthImageTopicName>
        <depthImageCameraInfoTopicName>camera/depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudTopicName>camera/depth/points</pointCloudTopicName>
        <pointCloudCutoff>0.2</pointCloudCutoff>
        <pointCloudCutoffMax>6.0</pointCloudCutoffMax>
      </plugin>
    </sensor>
  </gazebo>

</robot>
